<?php
return array (
  'sjs' => 
  array (
    'fieldid' => '157',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'sjs',
    'name' => '设计师',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'lpmc' => 
  array (
    'fieldid' => '158',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'lpmc',
    'name' => '楼盘名称',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'alfg' => 
  array (
    'fieldid' => '159',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'alfg',
    'name' => '案例风格',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u73b0\\u4ee3\\u7b80\\u7ea6|1\\r\\n\\u6b27\\u5f0f\\/\\u7b80\\u6b27|2\\r\\n\\u7530\\u56ed\\u98ce\\u683c|3\\r\\n\\u5730\\u4e2d\\u6d77\\u98ce\\u683c|4\\r\\n\\u4e2d\\u5f0f\\u98ce\\u683c|5\\r\\n\\u7f8e\\u5f0f\\u98ce\\u683c|6\\r\\n\\u6df7\\u642d\\u98ce\\u683c|7\\r\\n\\u5317\\u6b27\\u98ce\\u683c|8\\r\\n\\u5c40\\u90e8|9","boxtype":"select","fieldtype":"varchar","minnumber":"1","width":"80","size":"1","defaultvalue":"","outputtype":"1","filtertype":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '现代简约|1
欧式/简欧|2
田园风格|3
地中海风格|4
中式风格|5
美式风格|6
混搭风格|7
北欧风格|8
局部|9',
    'boxtype' => 'select',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
  'mj' => 
  array (
    'fieldid' => '160',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'mj',
    'name' => '面积',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'zxzj' => 
  array (
    'fieldid' => '161',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'zxzj',
    'name' => '装修造价',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'mjfw' => 
  array (
    'fieldid' => '162',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'mjfw',
    'name' => '面积范围',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"70\\u33a1\\u4ee5\\u4e0b|1\\r\\n70\\u33a1-100\\u33a1|2\\r\\n100\\u33a1-130\\u33a1|3\\r\\n130\\u33a1\\u4ee5\\u4e0a|4\\r\\n\\u522b\\u5885|5\\r\\n\\u65e0|6","boxtype":"select","fieldtype":"varchar","minnumber":"1","width":"80","size":"1","defaultvalue":"","outputtype":"1","filtertype":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '70㎡以下|1
70㎡-100㎡|2
100㎡-130㎡|3
130㎡以上|4
别墅|5
无|6',
    'boxtype' => 'select',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
  'hx' => 
  array (
    'fieldid' => '163',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'hx',
    'name' => '户型范围',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u4e00\\u5ba4|1\\r\\n\\u4e8c\\u5ba4|2\\r\\n\\u4e09\\u5ba4|3\\r\\n\\u56db\\u5ba4|4\\r\\n\\u65e0|5","boxtype":"select","fieldtype":"varchar","minnumber":"1","width":"80","size":"1","defaultvalue":"","outputtype":"1","filtertype":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '一室|1
二室|2
三室|3
四室|4
无|5',
    'boxtype' => 'select',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
  'nr' => 
  array (
    'fieldid' => '164',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'nr',
    'name' => '案例图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images',
    'setting' => '{"upload_allowext":"gif|jpg|jpeg|png|bmp","isselectimage":"1","upload_number":"10"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
    'isselectimage' => '1',
    'upload_number' => '10',
  ),
  'jubu' => 
  array (
    'fieldid' => '275',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'jubu',
    'name' => '局部',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u5ba2\\u5385|1\\r\\n\\u9910\\u5385|2\\r\\n\\u536b\\u751f\\u95f4|3\\r\\n\\u53a8\\u623f|4\\r\\n\\u5367\\u5ba4|5\\r\\n\\u9633\\u53f0|6\\r\\n\\u8fc7\\u9053|7\\r\\n\\u540a\\u9876|8\\r\\n\\u5426|9","boxtype":"select","fieldtype":"varchar","minnumber":"1","width":"80","size":"1","defaultvalue":"\\u5426|9","outputtype":"1","filtertype":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '客厅|1
餐厅|2
卫生间|3
厨房|4
卧室|5
阳台|6
过道|7
吊顶|8
否|9',
    'boxtype' => 'select',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '否|9',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
  'catid' => 
  array (
    'fieldid' => '136',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'catid',
    'name' => '栏目',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '6',
    'pattern' => '/^[0-9]{1,6}$/',
    'errortips' => '请选择栏目',
    'formtype' => 'catid',
    'setting' => 'array (
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'defaultvalue' => '',
  ),
  'typeid' => 
  array (
    'fieldid' => '137',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'typeid',
    'name' => '类别',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'typeid',
    'setting' => 'array (
  \'minnumber\' => \'\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '',
    'defaultvalue' => '',
  ),
  'title' => 
  array (
    'fieldid' => '138',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'title',
    'name' => '标题',
    'tips' => '',
    'css' => 'inputtitle',
    'minlength' => '1',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '请输入标题',
    'formtype' => 'title',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'keywords' => 
  array (
    'fieldid' => '139',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'keywords',
    'name' => '关键词',
    'tips' => '多关键词之间用空格或者“,”隔开',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '40',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'keyword',
    'setting' => 'array (
  \'size\' => \'100\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '7',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '100',
    'defaultvalue' => '',
  ),
  'description' => 
  array (
    'fieldid' => '140',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'description',
    'name' => '摘要',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '255',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'98\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '98',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
  'updatetime' => 
  array (
    'fieldid' => '141',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'updatetime',
    'name' => '更新时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'dateformat\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'1\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '12',
    'disabled' => '0',
    'isomnipotent' => '0',
    'dateformat' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '1',
    'defaultvalue' => '',
  ),
  'content' => 
  array (
    'fieldid' => '142',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'content',
    'name' => '案例说明',
    'tips' => '<div class="content_attr"><label><input name="add_introduce" type="checkbox"  value="1" checked>是否截取内容</label><input type="text" name="introcude_length" value="200" size="3">字符至内容摘要
<label><input type=\'checkbox\' name=\'auto_thumb\' value="1" checked>是否获取内容第</label><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为标题图片
</div>',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '999999',
    'pattern' => '',
    'errortips' => '内容不能为空',
    'formtype' => 'editor',
    'setting' => '{"toolbar":"full","defaultvalue":"","enablekeylink":"1","replacenum":"2","link_mode":"0","enablesaveimage":"1","height":"","disabled_page":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '13',
    'disabled' => '0',
    'isomnipotent' => '0',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '1',
    'replacenum' => '2',
    'link_mode' => '0',
    'enablesaveimage' => '1',
    'height' => '',
    'disabled_page' => '0',
  ),
  'thumb' => 
  array (
    'fieldid' => '143',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'thumb',
    'name' => '缩略图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'show_type\' => \'1\',
  \'upload_maxsize\' => \'1024\',
  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',
  \'watermark\' => \'0\',
  \'isselectimage\' => \'1\',
  \'images_width\' => \'\',
  \'images_height\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '14',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'show_type' => '1',
    'upload_maxsize' => '1024',
    'upload_allowext' => 'jpg|jpeg|gif|png|bmp',
    'watermark' => '0',
    'isselectimage' => '1',
    'images_width' => '',
    'images_height' => '',
  ),
  'relation' => 
  array (
    'fieldid' => '144',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'relation',
    'name' => '相关文章',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'<input type=\\\'hidden\\\' name=\\\'info[relation]\\\' id=\\\'relation\\\' value=\\\'{FIELD_VALUE}\\\' style=\\\'50\\\' >
<ul class="list-dot" id="relation_text"></ul>
<div>
<input type=\\\'button\\\' value="添加相关" onclick="omnipotent(\\\'selectid\\\',\\\'?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\',\\\'添加相关文章\\\',1)" class="button" style="width:66px;">
<span class="edit_content">
<input type=\\\'button\\\' value="显示已有" onclick="show_relation({MODELID},{ID})" class="button" style="width:66px;">
</span>
</div>\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '2,6,4,5,1,17,18,7',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '15',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<input type=\'hidden\' name=\'info[relation]\' id=\'relation\' value=\'{FIELD_VALUE}\' style=\'50\' >
<ul class="list-dot" id="relation_text"></ul>
<div>
<input type=\'button\' value="添加相关" onclick="omnipotent(\'selectid\',\'?m=content&c=content&a=public_relationlist&modelid={MODELID}\',\'添加相关文章\',1)" class="button" style="width:66px;">
<span class="edit_content">
<input type=\'button\' value="显示已有" onclick="show_relation({MODELID},{ID})" class="button" style="width:66px;">
</span>
</div>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'pages' => 
  array (
    'fieldid' => '145',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'pages',
    'name' => '分页方式',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'pages',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '16',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'inputtime' => 
  array (
    'fieldid' => '146',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'inputtime',
    'name' => '发布时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'fieldtype\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '17',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '0',
  ),
  'posids' => 
  array (
    'fieldid' => '147',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'posids',
    'name' => '推荐位',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'posid',
    'setting' => 'array (
  \'cols\' => \'4\',
  \'width\' => \'125\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '18',
    'disabled' => '0',
    'isomnipotent' => '0',
    'cols' => '4',
    'width' => '125',
  ),
  'groupids_view' => 
  array (
    'fieldid' => '148',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'groupids_view',
    'name' => '阅读权限',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'groupid',
    'setting' => 'array (
  \'groupids\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '19',
    'disabled' => '0',
    'isomnipotent' => '0',
    'groupids' => '',
  ),
  'islink' => 
  array (
    'fieldid' => '156',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'islink',
    'name' => '转向链接',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'islink',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '20',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'url' => 
  array (
    'fieldid' => '149',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'url',
    'name' => 'URL',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '50',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'listorder' => 
  array (
    'fieldid' => '150',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'listorder',
    'name' => '排序',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '6',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '51',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'template' => 
  array (
    'fieldid' => '151',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'template',
    'name' => '内容页模板',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '30',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '53',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '',
    'defaultvalue' => '',
  ),
  'allow_comment' => 
  array (
    'fieldid' => '152',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'allow_comment',
    'name' => '允许评论',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'允许评论|1
不允许评论|0\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'88\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '54',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '允许评论|1
不允许评论|0',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '88',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
  ),
  'status' => 
  array (
    'fieldid' => '153',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'status',
    'name' => '状态',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '2',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '55',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'readpoint' => 
  array (
    'fieldid' => '154',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'readpoint',
    'name' => '阅读收费',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '5',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'readpoint',
    'setting' => 'array (
  \'minnumber\' => \'1\',
  \'maxnumber\' => \'99999\',
  \'decimaldigits\' => \'0\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '55',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '1',
    'maxnumber' => '99999',
    'decimaldigits' => '0',
    'defaultvalue' => '',
  ),
  'username' => 
  array (
    'fieldid' => '155',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'username',
    'name' => '用户名',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '20',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '98',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
);
?>